[package]
name = "erdp"
description = "Crate for display an error and its nested errors"
version = "0.3.0"
license = "MIT"
repository = "https://github.com/ultimaweapon/erdp"
edition = "2024"
rust-version = "1.85"

[dependencies]

[dev-dependencies]
thiserror = "2.0.17"
